name: 'trunk-action'
description: 'Github action that installs and runs a trunk command'
author: 'udoprog'

inputs:
  args:
    description: 'The arguments to pass to `trunk`. Defaults to "build".'
    default: 'build'
  version:
    description: 'Version of wasm-bindgen to install like "v0.11.0". Defaults to "latest".'
    default: 'latest'
  wasm-bindgen-version:
    description: 'Version of wasm-bindgen to install like "0.2.73". Defaults to "latest".'
    default: 'latest'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'orange'
