name: 'trunk-action'
description: 'Github action that installs and runs a trunk command'
author: 'udoprog'

inputs:
  args:
    description: 'The arguments to pass to `trunk`. Defaults to "build --release".'
    default: 'build --release'
  version:
    description: 'Version of trunk to install like "v0.18.0". Defaults to "latest".'
    default: 'latest'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'orange'
